package the.md.project.wsproject.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import the.md.project.wsproject.PayerEssenceWebservice;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-08-13T16:32:17.214+02:00
 * Generated source version: 2.7.2
 * 
 */
@WebServiceClient(name = "PayerEssenceWebserviceImplService", 
                  wsdlLocation = "file:/D:/Capgemini/30_TestProject/20_Dev/03_Git/00_repository/git/ApacheCXF/payerEssenceClientWS/../payerEssenceWebService/src/main/resources/PayerEssenceWebserviceImpl.wsdl",
                  targetNamespace = "http://impl.wsProject.project.md.the/") 
public class PayerEssenceWebserviceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.wsProject.project.md.the/", "PayerEssenceWebserviceImplService");
    public final static QName PayerEssenceWebserviceImplPort = new QName("http://impl.wsProject.project.md.the/", "PayerEssenceWebserviceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Capgemini/30_TestProject/20_Dev/03_Git/00_repository/git/ApacheCXF/payerEssenceClientWS/../payerEssenceWebService/src/main/resources/PayerEssenceWebserviceImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PayerEssenceWebserviceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Capgemini/30_TestProject/20_Dev/03_Git/00_repository/git/ApacheCXF/payerEssenceClientWS/../payerEssenceWebService/src/main/resources/PayerEssenceWebserviceImpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PayerEssenceWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PayerEssenceWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayerEssenceWebserviceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PayerEssenceWebservice
     */
    @WebEndpoint(name = "PayerEssenceWebserviceImplPort")
    public PayerEssenceWebservice getPayerEssenceWebserviceImplPort() {
        return super.getPort(PayerEssenceWebserviceImplPort, PayerEssenceWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayerEssenceWebservice
     */
    @WebEndpoint(name = "PayerEssenceWebserviceImplPort")
    public PayerEssenceWebservice getPayerEssenceWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(PayerEssenceWebserviceImplPort, PayerEssenceWebservice.class, features);
    }

}
